import Head from 'next/head';
import type { ReactNode } from 'react';
import Navbar from '../Navbar';
import styles from './Layout.module.css';

interface Props {
  children: ReactNode;
  page: string;
}

const Layout: React.FC<Props> = ({ children, page }) => {
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Pagina de Agus - {page}</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
};

export default Layout;
